version: "3.7"
services:
        web:
                build: ./docker/nginx
                ports:
                        - "443:443"
        bot:
                build:
                        context: .
                        dockerfile: ./docker/bot/Dockerfile
                ports: 
                        - "6969:6969"

