name: CI

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run : |
        docker build -t unittest -f ./docker/tests/Dockerfile .
        docker run unittest
        
  checkCodeStyle:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
        
        
  docker-compose:
    runs-on: ubuntu-latest
    needs: [unittest, checkCodeStyle]
          
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker-compose
      run : |
        docker-compose -p tgbot build
    - name: push image
      run : |
        docker-compose push tgbot
 
