name: CI

on:
  push:
  pull_request:

jobs:
#  unittest:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: unittest
#       run : |
#         docker build -t unittest -f ./docker/tests/Dockerfile .
#         docker run unittest
        
#   checkCodeStyle:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: Python Style Checker
#       uses: andymckay/pycodestyle-action@0.1.3
      
#   docker-build:
#     runs-on: ubuntu-latest
#     needs: [unittest, checkCodeStyle]
          
#     steps:
#     - uses: actions/checkout@v2
#     - name: docker login
#       env:
#         DOCKER_USER: ${{ secrets.DOCKER_USER }}
#         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       run: |
#         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#     - name: build docker-compose
#       run : |
#         docker build -f ./docker/bot/Dockerfile -t xhazker/telegram-bot:0.1.0 .
#         docker build -f ./docker/bot/Dockerfile -t xhazker/nginx:0.1.0 .
#     - name: push image
#       run : |
#         docker push xhazker/telegram-bot:0.1.0
#         docker push xhazker/nginx:0.1.0
          
  run:
    runs-on: ubuntu-latest
#     needs: [unittest, checkCodeStyle, docker-build]
    
    steps:
      - name: ssh connect
        env:
          SSH: ${{ secrets.SSH}}
        run: |
          echo $SSH > key.pem
#          chmod 400 key.pem
#          ssh -y -i "key.pem" ubuntu@ec2-35-180-58-223.eu-west-3.compute.amazonaws.com
          
          
          
 
