name: CI

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run : |
        docker build -t unittest -f ./docker/tests/Dockerfile .
        docker run unittest
        
  checkCodeStyle:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
        
        
  docker-compose:
    runs-on: ubuntu-latest
    needs: [unittest, checkCodeStyle]
          
    steps:
    - uses: actions/checkout@v2
    - name: build docker-compose
      run : |
        docker-compose build
        
  deploy:
    runs-on: ubuntu-latest
    needs: [docker-compose]
    steps:
      - name: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          touch key.pem
          echo $SSH_KEY > key.pem
          ssh ubuntu@35.180.58.223 -i key.pem
 
