# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unittest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: unittest
      run : |
        cd tests
        docker -v
        
  docker-compose:
    runs-on: ubuntu-latest
    needs: [unittest]
          
    steps:
    - uses: actions/checkout@v2
      
    - name: Run apps in docker
      run : docker-compose build
